name: fotojenico
description: Which one is more fotojenico?

publish_to: 'none'

version: 0.2.1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  share: ^0.6.4+5
  camera: ^0.5.8+9
  video_player: ^0.11.0
  http: ^0.12.2
  provider: ^4.3.2+2
  path_provider:
  path:
  file_picker: ^2.0.4
  firebase_core: "0.5.0+1"
  firebase_analytics: "^6.0.2"
  firebase_admob: 0.10.0+2
  lit_firebase_auth: ^0.3.0
  flutter_settings_screens: ^0.2.1
  flutter_staggered_grid_view: ^0.3.2
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^1.0.0
  step_progress_indicator: ^0.2.4+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/loading2.gif

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
